import Link from 'next/link'
import type { Metadata } from 'next'
import { BrandLogo } from '@/components/brand/brand-logo'

export const metadata: Metadata = {
  title: 'Terms of Service - LunaCradle',
  description: 'Terms and conditions for using LunaCradle.',
}

export default function TermsPage() {
  return (
    <div className="marketing-shell min-h-screen bg-gradient-to-b from-sky-50 via-white to-rose-50 text-slate-900 dark:from-slate-950 dark:via-slate-900 dark:to-slate-950 dark:text-slate-100">
      <header className="container mx-auto px-4 py-6">
        <nav className="flex items-center justify-between rounded-3xl border border-white/60 bg-white/70 px-4 py-3 shadow-sm backdrop-blur dark:border-slate-700/70 dark:bg-slate-900/75">
          <Link href="/" className="flex items-center gap-2">
            <BrandLogo size={28} className="h-7 w-7" />
            <span className="text-lg font-semibold tracking-tight text-sky-800 dark:text-sky-200">LunaCradle</span>
          </Link>
          <div className="flex items-center gap-4 text-sm">
            <Link href="/privacy" className="text-slate-600 hover:text-slate-900 dark:text-slate-300 dark:hover:text-slate-100">Privacy</Link>
            <Link href="/contact" className="text-slate-600 hover:text-slate-900 dark:text-slate-300 dark:hover:text-slate-100">Contact</Link>
          </div>
        </nav>
      </header>

      <main className="container mx-auto max-w-3xl px-4 py-12">
        <h1 className="text-3xl font-semibold mb-2">Terms of Service</h1>
        <p className="text-sm text-slate-500 mb-10">Last updated: February 2026</p>

        <div className="space-y-8 text-slate-700 leading-relaxed">
          <section>
            <h2 className="text-xl font-semibold text-slate-900 mb-3">1. Acceptance of Terms</h2>
            <p className="text-sm">
              By accessing or using LunaCradle (&ldquo;the Service&rdquo;), you agree to be bound by these Terms of Service. If you do not agree to these terms, do not use the Service.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-slate-900 mb-3">2. Description of Service</h2>
            <p className="text-sm">
              LunaCradle provides AI-generated, personalized sleep guidance for parents and caregivers of infants and toddlers. The Service includes a sleep plan, a daily sleep diary, and weekly plan updates based on your logged data.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-slate-900 mb-3">3. Not Medical Advice</h2>
            <p className="text-sm">
              <strong>The Service is for educational and informational purposes only.</strong> It is not a substitute for professional medical advice, diagnosis, or treatment. Always consult your GP, health visitor, paediatrician, or a qualified healthcare provider with any questions about your child&apos;s health or sleep. Follow safe sleep guidelines from the NHS, AAP, and the Lullaby Trust at all times.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-slate-900 mb-3">4. Account &amp; Eligibility</h2>
            <p className="text-sm mb-3">To use the Service, you must:</p>
            <ul className="list-disc pl-6 space-y-1.5 text-sm">
              <li>Be at least 18 years of age.</li>
              <li>Create an account with accurate information.</li>
              <li>Keep your login credentials secure.</li>
            </ul>
            <p className="mt-3 text-sm">You are responsible for all activity under your account.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-slate-900 mb-3">5. Free Trial &amp; Subscription</h2>
            <ul className="list-disc pl-6 space-y-1.5 text-sm">
              <li>New users receive a <strong>5-day free trial</strong> with full access to all features.</li>
              <li>A valid credit card is required to start the trial.</li>
              <li>After the trial, your subscription automatically continues at <strong>$19 per month</strong> unless you cancel before the trial ends.</li>
              <li>You may cancel at any time from your account settings or by contacting support. Cancellation takes effect at the end of the current billing period.</li>
              <li>We do not offer refunds for partial billing periods, but you will retain access until the end of your paid period.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-slate-900 mb-3">6. AI-Generated Content</h2>
            <p className="text-sm">
              Sleep plans and recommendations are generated by artificial intelligence. While our guidance is grounded in established sleep research from leading organizations, AI-generated content may occasionally contain errors or suggestions that are not appropriate for every child. Always use your parental judgment and consult a healthcare professional when in doubt.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-slate-900 mb-3">7. Acceptable Use</h2>
            <p className="text-sm mb-3">You agree not to:</p>
            <ul className="list-disc pl-6 space-y-1.5 text-sm">
              <li>Use the Service for any unlawful purpose.</li>
              <li>Share, resell, or redistribute sleep plans or content.</li>
              <li>Attempt to reverse-engineer, scrape, or automate access to the Service.</li>
              <li>Provide false information in your account or intake forms.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-slate-900 mb-3">8. Intellectual Property</h2>
            <p className="text-sm">
              All content, design, and technology of LunaCradle is owned by us or our licensors. Your personalized sleep plan is generated for your personal, non-commercial use only. You may not copy, distribute, or republish any part of the Service without our written permission.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-slate-900 mb-3">9. Limitation of Liability</h2>
            <p className="text-sm">
              Nothing in these terms excludes or limits our liability for death or personal injury caused by our negligence, fraud or fraudulent misrepresentation, or any other liability that cannot be excluded or limited under English law. Subject to the foregoing, our total liability to you for all claims arising from or related to the Service shall not exceed the amount you paid us in the 12 months preceding the claim.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-slate-900 mb-3">10. Disclaimer of Warranties</h2>
            <p className="text-sm">
              The Service is provided &ldquo;as is&rdquo; and &ldquo;as available&rdquo; without warranties of any kind, either express or implied. We do not guarantee that the Service will be uninterrupted, error-free, or that results will meet your expectations.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-slate-900 mb-3">11. Changes to Terms</h2>
            <p className="text-sm">
              We may modify these terms at any time. We will notify you of material changes via email or an in-app notice. Continued use of the Service after changes constitutes acceptance of the updated terms.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-slate-900 mb-3">12. Termination</h2>
            <p className="text-sm">
              We reserve the right to suspend or terminate your account if you violate these terms. You may delete your account at any time by contacting support. Upon termination, your right to use the Service ceases and your data will be handled according to our Privacy Policy.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-slate-900 mb-3">13. Governing Law</h2>
            <p className="text-sm">
              These terms are governed by and construed in accordance with the laws of England and Wales. Any disputes arising from or related to these terms or the Service shall be subject to the exclusive jurisdiction of the courts of England and Wales. If you are a consumer, you may also benefit from any mandatory provisions of the law of the country in which you are resident.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-slate-900 mb-3">14. Company Information</h2>
            <p className="text-sm">
              LunaCradle is operated by a company registered in England and Wales. For company registration details or to exercise your statutory rights, please contact us through our{' '}
              <Link href="/contact" className="text-sky-700 hover:underline">contact form</Link>.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-slate-900 mb-3">15. Contact</h2>
            <p className="text-sm">
              Questions about these terms? Reach out through our{' '}
              <Link href="/contact" className="text-sky-700 hover:underline">contact form</Link>.
            </p>
          </section>
        </div>
      </main>

      <footer className="border-t border-white/70 py-8">
        <div className="container mx-auto px-4 text-center text-sm text-slate-500">
          &copy; {new Date().getFullYear()} LunaCradle. All rights reserved.
        </div>
      </footer>
    </div>
  )
}
