import { getResend, getFromEmail } from './resend'
import { sanitizeEmailSubject } from '@/lib/sanitize'

export async function sendFreeScheduleEmail(toEmail: string, pdfBytes: Uint8Array): Promise<void> {
  const resend = getResend()
  const fromEmail = getFromEmail()
  const appUrl = process.env.NEXT_PUBLIC_APP_URL || 'https://lunacradle.com'

  const html = `<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Your Free Baby Sleep Schedule</title>
  </head>
  <body style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; line-height: 1.6; color: #334155; max-width: 600px; margin: 0 auto; padding: 20px; background-color: #f8fafc;">
    <div style="background-color: #ffffff; border-radius: 12px; padding: 32px; box-shadow: 0 1px 3px rgba(0,0,0,0.08);">

      <div style="text-align: center; margin-bottom: 28px;">
        <h1 style="color: #0369a1; font-size: 24px; margin: 0 0 8px;">Your Sleep Schedule Is Here</h1>
        <p style="color: #64748b; margin: 0; font-size: 15px;">Generated by LunaCradle Free Schedule Builder</p>
      </div>

      <p style="margin: 0 0 16px;">Your personalised baby sleep schedule is attached as a PDF. Here's what it includes:</p>

      <div style="background-color: #f0fdf4; border: 1px solid #bbf7d0; border-radius: 8px; padding: 20px; margin: 0 0 24px;">
        <ul style="margin: 0; padding: 0 0 0 20px; color: #166534;">
          <li style="margin-bottom: 6px;">A sample daily schedule with specific times</li>
          <li style="margin-bottom: 6px;">Key guidance tailored to your baby's age</li>
          <li style="margin-bottom: 6px;">If/then adjustments for common situations</li>
          <li style="margin-bottom: 0;">What to do when things don't go to plan</li>
        </ul>
      </div>

      <p style="margin: 0 0 8px; color: #475569;">This schedule is a solid starting point. A full LunaCradle plan goes further with:</p>
      <ul style="margin: 0 0 24px; padding: 0 0 0 20px; color: #475569;">
        <li style="margin-bottom: 4px;">A step-by-step sleep method matched to your comfort level</li>
        <li style="margin-bottom: 4px;">A weekly diary that tracks progress and updates the plan</li>
        <li style="margin-bottom: 0;">Plan revisions as your baby grows and sleep needs change</li>
      </ul>

      <div style="text-align: center; margin: 28px 0;">
        <a href="${appUrl}/signup"
           style="background-color: #0369a1; color: #ffffff; padding: 14px 28px; text-decoration: none; border-radius: 8px; display: inline-block; font-weight: 600; font-size: 15px;">
          Get a Full Personalised Plan
        </a>
        <p style="margin: 12px 0 0; font-size: 13px; color: #94a3b8;">5-day free trial · $19/month · Cancel anytime</p>
      </div>

      <p style="margin: 0; color: #64748b; font-size: 14px;">Sweet dreams,<br><strong>The LunaCradle Team</strong></p>

      <hr style="border: none; border-top: 1px solid #e2e8f0; margin: 24px 0;">

      <p style="font-size: 12px; color: #94a3b8; margin: 0; text-align: center;">
        This schedule is for informational purposes only. Always follow your paediatrician's guidance and AAP safe sleep guidelines.
        <br>Generated by <a href="${appUrl}" style="color: #94a3b8;">LunaCradle</a>
      </p>

    </div>
  </body>
</html>`

  const text = `Your free baby sleep schedule is attached as a PDF.

It includes:
- A sample daily schedule with specific times
- Key guidance tailored to your baby's age
- If/then adjustments for common situations

For a full personalised plan with weekly diary tracking: ${appUrl}/signup

Sweet dreams,
The LunaCradle Team

---
This schedule is for informational purposes only. Not medical advice.
Generated by LunaCradle (${appUrl})`

  const { error } = await resend.emails.send({
    from: fromEmail,
    to: toEmail,
    subject: sanitizeEmailSubject('Your Free Baby Sleep Schedule from LunaCradle'),
    html,
    text,
    attachments: [
      {
        filename: 'LunaCradle_Free_Sleep_Schedule.pdf',
        content: Buffer.from(pdfBytes),
      },
    ],
  })

  if (error) {
    console.error('Failed to send free schedule email:', error)
    throw error
  }
}
